### ISSUE TITLE
Map overlays

### ISSUE THREAD

**Issue by danielfdsilva** [WorldBank-Transport/ram-frontend#144] opened 2017-08-08 10:23 UTC
Ability to overlay / toggle:
  - [x] destinations
 -  [x] origins
  - [x] admin boundaries
  - [x] road network

We have to consider some sort of tiling mechanism for the admin boundaries and road network, otherwise downloading the whole dataset will be too much.

**Comment by danielfdsilva** [comment] 2017-08-24 13:36
At least for the `admin boundaries` and `road network` we need to generate vector tiles. The files are too large to simply download and render.

Below are the results of some research and tests I've been doing.

> Note: When vector tiles are uploaded to S3 the `Content-Encoding` header must be set to `gzip` otherwise mapbox won't be able to render the `.pbf`

## Admin Boundaries

The admin boundaries are already in GeoJSON format so converting them to vector tiles is pretty simple using `tippecanoe -e [out folder] [file.geojson]`.

Todo for the admin boundaries:
- [ ] On project setup create the `.pbf` tiles and upload them to the storage under the path `project-[id]/admin-bounds/`
- [ ] Check if the storage can be accessed directly, otherwise create a proxy endpoint on the server. (Ensure correct `Content-Encoding`)
- [ ] Create a mapbox gl style for the admin boundaries

## Road Network

The road-network is proving to be a bit trickier to handle. @kamicut suggested to use [osmium-export](http://docs.osmcode.org/osmium/latest/osmium-export.html) to convert from the `.osm` to the `.geojson` used by `tippecanoe` but I wasn't able to install the tool. (I didn't have much time to look for them but I didn't find clear instructions.) @kamicut If you have the time could you write a quick note on how to install/use the tool?

Having failed with `osmium` I tried using `ogr2ogr` to convert the `.osm` to `.geojson`. This process works but, we can only export one data type at a time otherwise we get `ERROR 6: GeoJSON driver doesn't support creating more than one layer`.
So, basically the commands would be:
```
ogr2ogr -f GeoJSON points.json data.osm.pbf points
ogr2ogr -f GeoJSON lines.json data.osm.pbf lines
ogr2ogr -f GeoJSON multilinestrings.json data.osm.pbf multilinestrings
ogr2ogr -f GeoJSON multipolygons.json data.osm.pbf multipolygons
ogr2ogr -f GeoJSON other_relations.json data.osm.pbf other_relations
```
This exports `lines`, `points`... to individual files. It should be possible to use `tippecanoe` to re-join the files under different layers but I'm not sure.

This is what the road network for Sergipe look on the map (no style).
![image](https://user-images.githubusercontent.com/1090606/29665121-895e22dc-88ca-11e7-876a-ce3c980c2b21.png)


Todo for the road network:
- [ ] Figure out how to convert form `.osm` to `.geojson`
- [ ] When analysis is generated convert the road network to vector tiles and upload them to the storage under `scenario-[id]/road-network/`
- [ ] Check if the storage can be accessed directly, otherwise create a proxy endpoint on the server. (Ensure correct `Content-Encoding`)
- [ ] Create a style for the road-network. Maybe there's one available we can use? We'd have to figure out how to setup the layers and attributes in order for the style to work.

Overall the most challenging part seems to be: How do we convert the road network to geojson and then to vector tiles in such way that we can use some existing style so we don't have to manually style every road?

cc @olafveerman @kamicut

**Comment by kamicut** [comment] 2017-08-24 16:31
@danielfdsilva one other option would be to combine [osmconvert](http://wiki.openstreetmap.org/wiki/Osmconvert) and [tilemaker](https://github.com/systemed/tilemaker) to first turn the .osm to .osm.pbf then tile it. 

I have a couple of questions:
1. How often are these tiles generated / need to be replaced? Can you put the data into a postGIS db and serve it (maybe imposm or tileStache)? 
2. I don't understand what you mean by "manually style"? Are you styling different road attributes, and can you do that with GL styles on the frontend?

**Comment by danielfdsilva** [comment] 2017-09-07 14:07
@kamicut 
Answering your questions:
1 - The tiles would have to be generated every time that the road network changes. Since it's a process done by the user it's not possible to estimate.
2 - On the frontend we need to provide a gl style for the road network. To color the highways, secondary roads, and so on. Or am I missing something

**Comment by kamicut** [comment] 2017-09-07 15:17
@danielfdsilva Ok a few more questions
1. Can the user wait asynchronously for the tiling to happen or are they waiting on the page (what's the expectation on the frontend side)? 
2. Is the road network entirely replaced or can you generate a diff? My reasoning is that if there is a diff, we could possibly just run something like macrocosm + openroads-tiler. If not, we can use osmconvert + tilemaker
3. How big are the diffs or road networks?

For the GL styles, there are a bunch of FOSS ones (check out https://openmaptiles.org for preview)

**Comment by danielfdsilva** [comment] 2017-09-07 16:01
@kamicut 
1 - The process is done asynchronously, and a load message is displayed to the user. This will basically tie in with the analysis generation. They can change page and come back later to see the result.
2 - Only part would change, depends on the user.
3 - I'd say we should expect road networks of close to 1GB

**Comment by kamicut** [comment] 2017-09-07 21:04
@danielfdsilva for 1GB I think `osmconvert` and `tilemaker` should work fine if you're processing the entire network. You can then have a small server like `tessera` to serve the mbtiles, or copy them to an S3 bucket.

**Comment by kamicut** [comment] 2017-09-11 19:27
@danielfdsilva I was able to convert the Sergpipe RN using [`osmium-tool`](http://osmcode.org/osmium-tool/manual.html#osm-file-formats-and-converting-between-them) and then using `tilemaker`. I think the problem is that `osmconvert` expects the data to be in a certain format (ids should be sorted). `osmium-tool` doesn't have that requirement.

![Sergipe RN map](https://api.mapbox.com/styles/v1/devseed/cj7ginb4o02z92rmyyq520ksi/static/-37.838774,-11.157667,7.64,0.00,0.00/600x400?access_token=pk.eyJ1IjoiZGV2c2VlZCIsImEiOiJnUi1mbkVvIn0.018aLhX0Mb0tdtaT2QNe2Q)

**Comment by danielfdsilva** [comment] 2017-09-12 09:23
@kamicut That's great! could you give a quick writeup of how to install osmium (specially what libs are needed) and what the commands to generate the files are?

**Comment by olafveerman** [comment] 2017-10-03 14:08
Fixed with: https://github.com/WorldBank-Transport/ram-frontend/commit/642f4d518beaa0819511d8454b34c2f47c39a626

**Closed by olafveerman** 2017-10-03 14:08 UTC
